name: Fetching CloudFormation resource specification and update this VSCode extension.
schedule:
  - cron: "10 11 * * 5" # At 11:10 on Friday.
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python and NPM requirements
        run: |
          python -m pip install --upgrade pip && pip install -r src/requirements.txt
          npm install -g vsce
      - name: Check for update and create snippets if needed
        run: |
          echo "checking for update"
          python src/update-cfn-resource-snippets.py
      - name: Commit changes and publish package VSCode Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: |
          set -x -e
          git config --global user.name 'danny@s.cloud'
          git config --global user.email 'Github Actions'
          npm version minor --force --no-git-tag-version
          package_version=$(cat package.json|grep version|sed 's/[",]//g'|awk '{print $2}')
          cfn_release_rss_summary=$(python src/feed.py)
          git commit -am "$cfn_release_rss_summary"
          git tag $package_version
          gitchangelog|tee "CHANGELOG.md"
          git commit -am "Changelog version: $package_version"
          git push
          git push origin --tags
          vsce package
          vsce publish -p $VSCE_TOKEN
